//! Golden test for the `Markdown` component (markdown.rs) against the oracle
//! fixture `tests/fixtures/pi/tui/markdown.cases.jsonl` (real Pi `Markdown`
//! render() output, generated by `scripts/gen-tui-oracle.mjs`).
//!
//! The fixture uses a deterministic fake theme (fixed SGR codes) so the
//! comparison is byte-exact.

use std::rc::Rc;

use pirust_tui::markdown::{Markdown, MarkdownTheme};
use serde_json::Value;

fn fixture_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tests/fixtures/pi/tui/markdown.cases.jsonl")
}

/// The deterministic theme the oracle used: each fn wraps text in a fixed
/// SGR sequence.
fn oracle_theme() -> MarkdownTheme {
    let sgr = |code: &'static str| Rc::new(move |text: &str| format!("\x1b[{code}m{text}\x1b[0m"));
    MarkdownTheme {
        heading: sgr("1;36"),
        link: sgr("34"),
        link_url: sgr("2"),
        code: sgr("33"),
        code_block: sgr("32"),
        code_block_border: sgr("2"),
        quote: sgr("3"),
        quote_border: sgr("2"),
        hr: sgr("2"),
        list_bullet: sgr("36"),
        bold: sgr("1"),
        italic: sgr("3"),
        strikethrough: sgr("9"),
        underline: sgr("4"),
    }
}

#[test]
fn every_markdown_record_matches_pi() {
    let contents = std::fs::read_to_string(fixture_path()).expect("fixture missing");
    let records: Vec<Value> = contents
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();
    assert!(!records.is_empty(), "fixture should have records");

    let theme = oracle_theme();
    let mut failures: Vec<String> = Vec::new();

    for record in &records {
        let note = record["note"].as_str().unwrap();
        let text = record["text"].as_str().unwrap();
        let width = record["width"].as_u64().unwrap() as usize;
        let options = &record["options"];
        let expected_render: Vec<String> = record["render"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap().to_string())
            .collect();

        let opts = if options.is_null() {
            None
        } else {
            Some(pirust_tui::markdown::MarkdownOptions {
                preserve_ordered_list_markers: options["preserveOrderedListMarkers"]
                    .as_bool()
                    .unwrap_or(false),
                preserve_backslash_escapes: options["preserveBackslashEscapes"]
                    .as_bool()
                    .unwrap_or(false),
                render_latex: options["renderLatex"].as_bool().unwrap_or(true),
            })
        };

        let mut md = Markdown::new(text, 0, 0, theme.clone(), None, opts);
        let actual = md.render(width);

        if actual != expected_render {
            failures.push(format!(
                "\n[{note}] render mismatch (width {width}):\n  expected {} lines, got {}\n  expected: {:?}\n  actual:   {:?}",
                expected_render.len(),
                actual.len(),
                expected_render,
                actual
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} markdown record(s) diverged from Pi:{}",
        failures.len(),
        failures.join("\n")
    );
}
