//! Byte-compatibility tests against real Pi output (the oracle).
//!
//! Each case deserializes a vendored Pi fixture into a pirust-ai type and asserts the
//! re-serialized compact JSON is byte-identical to the `.golden` — the exact bytes JS
//! `JSON.stringify(JSON.parse(fixture))` produces (see `scripts/gen-golden.mjs`).
//!
//! This is what proves the port matches Pi, as opposed to matching our own expectations.

use std::path::PathBuf;

use pirust_ai::types::{AssistantMessageEvent, Message, Model};

fn fixtures_dir() -> PathBuf {
    // CARGO_MANIFEST_DIR = crates/pirust-ai
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/pi")
}

fn load(name: &str) -> (String, String) {
    let dir = fixtures_dir();
    let input = std::fs::read_to_string(dir.join(format!("{name}.json")))
        .unwrap_or_else(|e| panic!("read fixture {name}.json: {e}"));
    let golden = std::fs::read_to_string(dir.join(format!("{name}.golden"))).unwrap_or_else(|e| {
        panic!("read golden {name}.golden ({e}); run: node scripts/gen-golden.mjs")
    });
    (input, golden)
}

#[test]
fn assistant_message_with_thinking_code_is_byte_identical() {
    let (input, golden) = load("assistant-message-with-thinking-code");
    let msg: Message =
        serde_json::from_str(&input).expect("deserialize real Pi AssistantMessage fixture");
    let reserialized = serde_json::to_string(&msg).expect("serialize");
    assert_eq!(
        reserialized, golden,
        "pirust re-serialization must be byte-identical to Pi's JSON.stringify output"
    );
}

/// Round-trips every real pi-ai Message (user/assistant/toolResult) extracted from Pi
/// session fixtures. Each corpus line is JS-canonical `JSON.stringify(message)`; our
/// deserialize→serialize must reproduce it byte-for-byte. Generated by
/// `scripts/gen-message-corpus.mjs`.
#[test]
fn message_corpus_is_byte_identical() {
    let path = fixtures_dir().join("messages.corpus.jsonl");
    let corpus = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("read corpus ({e}); run: node scripts/gen-message-corpus.mjs"));

    let mut failures: Vec<String> = Vec::new();
    let mut count = 0usize;
    for (i, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        count += 1;
        let msg: Message = match serde_json::from_str(line) {
            Ok(m) => m,
            Err(e) => {
                failures.push(format!("line {}: deserialize failed: {e}", i + 1));
                continue;
            }
        };
        let out = serde_json::to_string(&msg).expect("serialize");
        if out != line {
            failures.push(format!("line {}: {}", i + 1, first_diff(line, &out)));
        }
    }

    assert!(count > 0, "corpus is empty");
    if !failures.is_empty() {
        let shown = failures
            .iter()
            .take(6)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "{}/{} messages diverged from Pi:\n{}",
            failures.len(),
            count,
            shown
        );
    }
}

/// Every real Pi Model (generated catalog, 1000+ models across ~35 providers) must
/// round-trip through the `Model` type with no field dropped and no value changed.
///
/// This is a **semantic** (order-independent) check, not byte-identity: Pi's Model JSON
/// key order is not canonical (it varies per provider/model), and Models are never
/// persisted per-session, so byte-identity is neither achievable nor required. What
/// matters is that the type faithfully captures every real Model losslessly.
#[test]
fn model_corpus_lossless_semantic_roundtrip() {
    let path = fixtures_dir().join("models.corpus.jsonl");
    let corpus = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read model corpus ({e}); run: node scripts/gen-model-corpus.mjs")
    });

    let mut failures: Vec<String> = Vec::new();
    let mut count = 0usize;
    for (i, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        count += 1;
        let original: serde_json::Value =
            serde_json::from_str(line).expect("fixture is valid JSON");
        let model: Model = match serde_json::from_str(line) {
            Ok(m) => m,
            Err(e) => {
                failures.push(format!("line {}: parse Model failed: {e}", i + 1));
                continue;
            }
        };
        let out = serde_json::to_string(&model).expect("serialize");
        let reparsed: serde_json::Value =
            serde_json::from_str(&out).expect("our output is valid JSON");
        // Value equality is order-independent (semantic): catches dropped fields and
        // changed values without demanding Pi's (non-canonical) key order.
        if original != reparsed {
            failures.push(format!(
                "line {}: semantic mismatch\n  {}",
                i + 1,
                first_diff(line, &out)
            ));
        }
    }

    assert!(count > 1000, "expected 1000+ models, got {count}");
    if !failures.is_empty() {
        let shown = failures
            .iter()
            .take(6)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "{}/{} models did not round-trip losslessly:\n{}",
            failures.len(),
            count,
            shown
        );
    }
}

/// Every real Pi AssistantMessageEvent (captured from Pi's own faux provider — the real
/// event-emitting code path) must round-trip through the `AssistantMessageEvent` type
/// with no field dropped and no value changed.
///
/// Semantic (order-independent), not byte-identity: events are streamed, never persisted,
/// and the nested `partial`/`message` AssistantMessage carries the *producing* code path's
/// key order (which is not the canonical persisted order). What this proves is that the
/// event type faithfully captures every real event losslessly. The fixture is a frozen
/// capture (`events.corpus.jsonl`) — non-deterministic ids/timestamps mean it is not
/// regenerated on --check.
#[test]
fn event_corpus_lossless_semantic_roundtrip() {
    let path = fixtures_dir().join("events.corpus.jsonl");
    let corpus =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read event corpus ({e})"));

    let mut failures: Vec<String> = Vec::new();
    let mut count = 0usize;
    let mut seen_types = std::collections::BTreeSet::new();
    for (i, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        count += 1;
        let original: serde_json::Value =
            serde_json::from_str(line).expect("fixture is valid JSON");
        if let Some(t) = original.get("type").and_then(|t| t.as_str()) {
            seen_types.insert(t.to_string());
        }
        let ev: AssistantMessageEvent = match serde_json::from_str(line) {
            Ok(e) => e,
            Err(e) => {
                failures.push(format!("line {}: parse event failed: {e}", i + 1));
                continue;
            }
        };
        let out = serde_json::to_string(&ev).expect("serialize");
        let reparsed: serde_json::Value =
            serde_json::from_str(&out).expect("our output is valid JSON");
        if original != reparsed {
            failures.push(format!(
                "line {}: semantic mismatch\n  {}",
                i + 1,
                first_diff(line, &out)
            ));
        }
    }

    assert!(count > 0, "event corpus is empty");
    // Guard against silent coverage loss: all 12 event variants must be exercised.
    let expected = [
        "start",
        "text_start",
        "text_delta",
        "text_end",
        "thinking_start",
        "thinking_delta",
        "thinking_end",
        "toolcall_start",
        "toolcall_delta",
        "toolcall_end",
        "done",
        "error",
    ];
    let missing: Vec<&str> = expected
        .iter()
        .copied()
        .filter(|t| !seen_types.contains(*t))
        .collect();
    assert!(
        missing.is_empty(),
        "event corpus missing variants: {missing:?}"
    );
    if !failures.is_empty() {
        let shown = failures
            .iter()
            .take(6)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n");
        panic!(
            "{}/{} events did not round-trip losslessly:\n{}",
            failures.len(),
            count,
            shown
        );
    }
}

/// Type-fidelity check for Message fields absent from the real session fixtures
/// (image content, textSignature, redacted, thoughtSignature, usage.reasoning/cacheWrite1h,
/// responseModel/responseId/diagnostics, addedToolNames, user string content).
///
/// Shapes follow `types.ts` and are serialized by real Node `JSON.stringify`
/// (`scripts/gen-rarefields-corpus.mjs`). Semantic (order-independent) round-trip proves
/// the pirust types capture every such field losslessly. Persisted byte-ORDER of these
/// fields is pinned later, when the runtime produces + persists them (feat-002/003) —
/// no real session contains them today.
#[test]
fn rarefields_lossless_semantic_roundtrip() {
    let path = fixtures_dir().join("rarefields.corpus.jsonl");
    let corpus = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read rare-fields corpus ({e}); run: node scripts/gen-rarefields-corpus.mjs")
    });

    let raw = corpus.replace('\n', "");
    // Coverage guard: the corpus must actually exercise each target field.
    for needle in [
        "\"mimeType\"",         // ImageContent
        "\"textSignature\"",    // TextContent.textSignature
        "\"redacted\"",         // ThinkingContent.redacted
        "\"thoughtSignature\"", // ToolCall.thoughtSignature
        "\"reasoning\"",        // Usage.reasoning
        "\"cacheWrite1h\"",     // Usage.cacheWrite1h
        "\"responseModel\"",    // AssistantMessage.responseModel
        "\"responseId\"",       // AssistantMessage.responseId
        "\"diagnostics\"",      // AssistantMessage.diagnostics
        "\"addedToolNames\"",   // ToolResultMessage.addedToolNames
    ] {
        assert!(
            raw.contains(needle),
            "rare-fields corpus does not exercise {needle}"
        );
    }

    let mut failures: Vec<String> = Vec::new();
    let mut count = 0usize;
    for (i, line) in corpus.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        count += 1;
        let original: serde_json::Value =
            serde_json::from_str(line).expect("fixture is valid JSON");
        let msg: Message = match serde_json::from_str(line) {
            Ok(m) => m,
            Err(e) => {
                failures.push(format!("line {}: parse Message failed: {e}", i + 1));
                continue;
            }
        };
        let out = serde_json::to_string(&msg).expect("serialize");
        let reparsed: serde_json::Value =
            serde_json::from_str(&out).expect("our output is valid JSON");
        if original != reparsed {
            failures.push(format!(
                "line {}: semantic mismatch\n  {}",
                i + 1,
                first_diff(line, &out)
            ));
        }
    }

    assert_eq!(count, 5, "expected 5 rare-field messages");
    if !failures.is_empty() {
        panic!(
            "{}/{} rare-field messages did not round-trip losslessly:\n{}",
            failures.len(),
            count,
            failures.join("\n")
        );
    }
}

/// Locate the first byte where two strings differ and show a window around it from each.
fn first_diff(pi: &str, pirust: &str) -> String {
    let pb = pi.as_bytes();
    let rb = pirust.as_bytes();
    let mut i = 0;
    while i < pb.len() && i < rb.len() && pb[i] == rb[i] {
        i += 1;
    }
    let start = i.saturating_sub(30);
    let win = |s: &str, from: usize| -> String {
        let end = (from + 70).min(s.len());
        // snap to char boundaries
        let mut a = from;
        while a < s.len() && !s.is_char_boundary(a) {
            a -= 1;
        }
        let mut b = end;
        while b < s.len() && !s.is_char_boundary(b) {
            b += 1;
        }
        s[a..b].escape_debug().to_string()
    };
    format!(
        "first diff at byte {i} (pi len {}, pirust len {})\n  pi:     …{}…\n  pirust: …{}…",
        pb.len(),
        rb.len(),
        win(pi, start),
        win(pirust, start),
    )
}
