//! Golden streaming-tape tests for the `openai-completions` stream adapter
//! (`streamSimple`), against real Pi output (the oracle).
//!
//! Fixtures: `tests/fixtures/pi/openai-completions/cases.jsonl`, generated by
//! `scripts/gen-openai-completions-oracle.mjs` which drives Pi's REAL
//! `streamSimple` with a fake `fetch` returning a canned OpenAI chat-completions
//! SSE body. Each `stream` record stores `sseBody` (the exact bytes fed), the
//! emitted event tape (type sequence + emission-stable fields; `partial`
//! excluded — see below), and the final `AssistantMessage` (byte-compared).
//!
//! This test reconstructs the scenario inputs (real model from
//! `models.corpus.jsonl`, matching context), feeds the SAME `sseBody` through
//! the Rust `stream_simple` via a `CannedTransport`, and asserts:
//! - the final message serializes byte-identically to Pi's literal `final`
//!   capture (float format, key order, dropped/extra fields),
//! - the emitted tape's type sequence and stable fields match Pi's.
//!
//! ## `partial` is not compared (same divergence as anthropic_golden.rs)
//!
//! Pi pushes one mutable `output` by reference into every event, so a captured
//! tape's `partial` is the FINAL message (JS aliasing); a faithful Rust port
//! emits owned incremental snapshots. Only the TERMINAL event's message/error
//! (which equals the final message) is byte-compared.

use std::path::PathBuf;

use futures::StreamExt;
use pirust_ai::api::openai_completions::stream_simple;
use pirust_ai::http::CannedTransport;
use pirust_ai::types::event::AssistantMessageEvent;
use pirust_ai::types::message::{
    Context, Message, Tool, UserMessage, UserMessageContent, UserRole,
};
use pirust_ai::types::model::Model;
use serde_json::{json, Value};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/pi")
}

/// Load a real `Model` from the vendored `models.corpus.jsonl` by (provider, id)
/// — the same catalog the oracle's `getModel()` reads from — so cost rates and
/// compat match Pi's real model data. The `baseUrl` is overridden to match the
/// oracle (which points at the fake client).
fn lookup_model(provider: &str, id: &str) -> Model {
    let path = fixtures_dir().join("models.corpus.jsonl");
    let text =
        std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read models {path:?} ({e})"));
    for line in text.lines().filter(|l| !l.trim().is_empty()) {
        let v: Value = serde_json::from_str(line).expect("model line JSON");
        if v["provider"] == provider && v["id"] == id {
            let mut model: Model = serde_json::from_value(v).expect("deserialize Model");
            model.base_url = "http://127.0.0.1:9/v1".into();
            return model;
        }
    }
    panic!("model {provider}/{id} not in {path:?}")
}

fn user_msg(timestamp: i64, content: &str) -> Message {
    Message::User(UserMessage {
        role: UserRole::User,
        content: UserMessageContent::Text(content.to_string()),
        timestamp,
    })
}

fn tool(name: &str) -> Tool {
    Tool {
        name: name.to_string(),
        description: format!("The {name} tool"),
        parameters: json!({
            "type": "object",
            "required": ["value"],
            "properties": { "value": { "type": "string" } }
        }),
        constrained_sampling: None,
    }
}

/// Reconstruct the model + context for a stream scenario (mirrors the oracle's
/// `streamScenarios` definitions).
fn scenario_inputs(name: &str) -> (Model, Context) {
    match name {
        "text-stream" => (
            lookup_model("together", "meta-llama/Llama-3.3-70B-Instruct-Turbo"),
            Context {
                system_prompt: None,
                messages: vec![user_msg(1, "hi")],
                tools: None,
            },
        ),
        "tool-call-stream" => (
            lookup_model("together", "meta-llama/Llama-3.3-70B-Instruct-Turbo"),
            Context {
                system_prompt: None,
                messages: vec![user_msg(1, "use the tool")],
                tools: Some(vec![tool("base_tool")]),
            },
        ),
        "thinking-reasoning" => (
            lookup_model("deepseek", "deepseek-v4-flash"),
            Context {
                system_prompt: None,
                messages: vec![user_msg(1, "think hard")],
                tools: None,
            },
        ),
        _ => panic!("unknown stream scenario {name}"),
    }
}

/// Simplify the Rust event for comparison against Pi's tape: serialize to a
/// `Value`, drop the `partial` field (the documented alias divergence), and
/// zero any nested `timestamp` (the oracle zeroes `final.timestamp`, which in
/// JS is the SAME object as the terminal event's message — so the tape's
/// terminal events carry `timestamp: 0`).
fn event_without_partial(event: &AssistantMessageEvent) -> Value {
    let mut v = serde_json::to_value(event).expect("event to value");
    if let Some(obj) = v.as_object_mut() {
        obj.remove("partial");
        if obj.contains_key("message") || obj.contains_key("error") {
            for key in ["message", "error"] {
                if let Some(msg) = obj.get_mut(key).and_then(Value::as_object_mut) {
                    if let Some(ts) = msg.get_mut("timestamp") {
                        *ts = json!(0);
                    }
                }
            }
        }
    }
    v
}

/// Serialize the final message with jsnum precision (the crate's own
/// `serialize`) so floats/key-order match Pi's literal bytes.
fn message_json(message: &pirust_ai::types::message::AssistantMessage) -> Value {
    serde_json::to_value(message).expect("message to value")
}

#[tokio::test]
async fn golden_streams() {
    // load all stream records
    let path = fixtures_dir().join("openai-completions/cases.jsonl");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read {path:?} ({e}); run: node scripts/gen-openai-completions-oracle.mjs")
    });
    let records: Vec<(String, Value)> = text
        .lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| {
            let v: Value = serde_json::from_str(l).expect("fixture line JSON");
            if v["section"] == "stream" {
                Some((
                    v["name"].as_str().unwrap().to_string(),
                    v["payload"].clone(),
                ))
            } else {
                None
            }
        })
        .collect();

    assert!(
        records.len() >= 3,
        "expected at least 3 stream fixtures, got {}",
        records.len()
    );

    let mut checked = 0;
    for (name, payload) in records {
        let sse_body = payload["sseBody"].as_str().expect("sseBody");
        let (model, context) = scenario_inputs(&name);

        // feed the canned SSE body through the SAME TS path (`streamSimple`),
        // with the transport injected on the shared base options
        let mut simple = pirust_ai::api::SimpleStreamOptions::default();
        simple.base.api_key = Some("fake-key".to_string());
        simple.base.transport = Some(
            std::sync::Arc::new(CannedTransport::new(sse_body.to_string()))
                as std::sync::Arc<dyn pirust_ai::http::DynTransport>,
        );
        let mut event_stream = stream_simple(&model, &context, Some(simple));

        let mut tape: Vec<AssistantMessageEvent> = Vec::new();
        while let Some(event) = event_stream.next().await {
            tape.push(event);
        }
        let final_message = event_stream.result().await;

        // --- FINAL message byte-identical to Pi's literal capture ---
        let mut actual_final = message_json(&final_message);
        if let Some(ts) = actual_final.get_mut("timestamp") {
            *ts = json!(0);
        }
        assert_eq!(
            actual_final, payload["final"],
            "[{name}] final message must byte-match Pi's literal capture"
        );

        // --- TAPE: type sequence + stable fields; skip partial ---
        let expected_tape = payload["events"].as_array().expect("events array");
        assert_eq!(
            tape.len(),
            expected_tape.len(),
            "[{name}] tape length mismatch"
        );
        for (i, (event, expected)) in tape.iter().zip(expected_tape).enumerate() {
            let actual = event_without_partial(event);
            assert_eq!(actual, *expected, "[{name}] tape event {i} mismatch");
        }

        // --- TERMINAL event's message byte-matches Pi's literal final bytes ---
        let terminal = tape.last().expect("non-empty tape");
        let terminal_message = match terminal {
            AssistantMessageEvent::Done { message, .. } => message,
            AssistantMessageEvent::Error { error, .. } => error,
            _ => panic!("terminal event is not done/error"),
        };
        let mut terminal_msg = message_json(terminal_message);
        if let Some(ts) = terminal_msg.get_mut("timestamp") {
            *ts = json!(0);
        }
        assert_eq!(
            terminal_msg, payload["final"],
            "[{name}] terminal event message must byte-match Pi's literal final"
        );

        checked += 1;
    }
    eprintln!("openai-completions stream golden: {checked} scenarios byte-verified");
}
