//! Golden tests for the `openai-responses` adapter against real Pi output (the oracle).
//!
//! Fixtures: `tests/fixtures/pi/openai-responses/cases.jsonl`, generated by
//! `scripts/gen-openai-responses-oracle.mjs`. Three sections:
//! - `convertMessages`: `convert_responses_messages` → compact JSON byte-identical.
//! - `convertTools`: `convert_responses_tools` → compact JSON byte-identical.
//! - `stream`: canned SSE → event tape (type + stable fields, `partial` excluded) +
//!   final `AssistantMessage` byte-identical.
//!
//! `partial` is not compared for the same reason as the anthropic/openai-completions
//! goldens: Pi pushes one mutable `output` by reference into every event (JS aliasing),
//! so a captured tape's `partial` is the FINAL message; the Rust port emits owned
//! incremental snapshots. Only the terminal event's message (== the final message) is
//! byte-compared.

use std::collections::HashSet;
use std::path::PathBuf;

use futures::StreamExt;
use pirust_ai::api::openai_responses_shared::{
    convert_responses_messages, convert_responses_tools, ConvertResponsesMessagesOptions,
    ConvertResponsesToolsOptions, DeferredToolsMode,
};
use pirust_ai::api::SimpleStreamOptions;
use pirust_ai::http::CannedTransport;
use pirust_ai::types::content::{AssistantContent, TextContent, ToolCall, UserContent};
use pirust_ai::types::event::AssistantMessageEvent;
use pirust_ai::types::ids::{Api, ProviderId, StopReason};
use pirust_ai::types::message::{
    AssistantMessage, Context, Message, Tool, ToolResultMessage, UserMessage, UserMessageContent,
    UserRole,
};
use pirust_ai::types::model::{Model, ModelCost, ModelCostRates};
use serde_json::{json, Map, Value};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/pi")
}

fn load_records() -> Vec<(String, String, Value)> {
    let path = fixtures_dir().join("openai-responses/cases.jsonl");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read {path:?} ({e}); run: node scripts/gen-openai-responses-oracle.mjs")
    });
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            let v: Value = serde_json::from_str(l).expect("fixture line is JSON");
            let section = v["section"].as_str().unwrap().to_string();
            let name = v["name"].as_str().unwrap().to_string();
            (section, name, v["payload"].clone())
        })
        .collect()
}

// --- Reconstruction helpers (mirror the oracle script's model/builder shapes) --------

/// The `openaiModel("gpt-5.2")` used by the oracle, with baseUrl overridden to the fake.
fn openai_model() -> Model {
    Model {
        id: "gpt-5.2".into(),
        name: "GPT-5.2".into(),
        api: Api::from("openai-responses"),
        provider: ProviderId::from("openai"),
        base_url: "https://api.openai.com/v1".into(),
        reasoning: true,
        thinking_level_map: None,
        input: vec![
            pirust_ai::types::model::Modality::Text,
            pirust_ai::types::model::Modality::Image,
        ],
        cost: ModelCost {
            rates: ModelCostRates {
                input: 1.75,
                output: 14.0,
                cache_read: 0.175,
                cache_write: 0.0,
            },
            tiers: None,
        },
        context_window: 400_000,
        max_tokens: 128_000,
        headers: None,
        compat: Some(json!({
            "supportsStrictMode": true,
            "supportsOpenAIGrammarTools": true
        })),
    }
}

fn usage0() -> pirust_ai::types::usage::Usage {
    pirust_ai::types::usage::Usage {
        input: 0,
        output: 0,
        cache_read: 0,
        cache_write: 0,
        cache_write1h: None,
        reasoning: None,
        total_tokens: Some(0),
        cost: pirust_ai::types::usage::Cost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
            total: 0.0,
        },
    }
}

fn assistant_message(
    content: Vec<AssistantContent>,
    api: &str,
    provider: &str,
    model: &str,
) -> AssistantMessage {
    AssistantMessage {
        role: pirust_ai::types::message::AssistantRole::Assistant,
        content,
        api: Api::from(api),
        provider: ProviderId::from(provider),
        model: Some(model.into()),
        response_model: None,
        diagnostics: None,
        usage: usage0(),
        stop_reason: StopReason::Stop,
        timestamp: 2,
        response_id: None,
        raw_stop_reason: None,
        error_message: None,
        end_turn: None,
    }
}

fn user_msg(timestamp: i64, content: &str) -> Message {
    Message::User(UserMessage {
        role: UserRole::User,
        content: UserMessageContent::Text(content.to_string()),
        timestamp,
    })
}

fn text_content(text: &str, text_signature: Option<&str>) -> AssistantContent {
    AssistantContent::Text(TextContent {
        kind: pirust_ai::types::content::TextTag::Text,
        text: text.to_string(),
        text_signature: text_signature.map(String::from),
    })
}

fn tool_call_content(id: &str, name: &str, arguments: Map<String, Value>) -> AssistantContent {
    AssistantContent::ToolCall(ToolCall {
        kind: pirust_ai::types::content::ToolCallTag::ToolCall,
        id: id.to_string(),
        name: name.to_string(),
        arguments,
        thought_signature: None,
        namespace: None,
        partial_json: None,
    })
}

fn tool_result(
    tool_call_id: &str,
    tool_name: &str,
    content: Vec<UserContent>,
    added: Option<Vec<String>>,
) -> Message {
    Message::ToolResult(ToolResultMessage {
        role: pirust_ai::types::message::ToolResultRole::ToolResult,
        tool_call_id: tool_call_id.to_string(),
        tool_name: tool_name.to_string(),
        content,
        details: None,
        added_tool_names: added,
        is_error: false,
        timestamp: 3,
    })
}

fn tool(name: &str) -> Tool {
    Tool {
        name: name.to_string(),
        description: format!("The {name} tool"),
        parameters: json!({
            "type": "object",
            "required": ["value"],
            "properties": { "value": { "type": "string" } }
        }),
        constrained_sampling: None,
    }
}

fn grammar_tool() -> Tool {
    Tool {
        name: "grammar_tool".into(),
        description: "Grammar tool".into(),
        parameters: json!({
            "type": "object",
            "required": ["value"],
            "properties": { "value": { "type": "string" } }
        }),
        constrained_sampling: Some(
            pirust_ai::types::message::ConstrainedSamplingConfig::Grammar {
                variants: pirust_ai::types::message::GrammarVariants {
                    openai_lark: Some("start: \"hello\"".into()),
                    openai_regex: None,
                },
            },
        ),
    }
}

fn text(block: &str) -> UserContent {
    UserContent::Text(TextContent::new(block))
}

fn image(data: &str) -> UserContent {
    UserContent::Image(pirust_ai::types::content::ImageContent {
        kind: pirust_ai::types::content::ImageTag::Image,
        data: data.to_string(),
        mime_type: "image/png".into(),
    })
}

fn allowed_providers() -> HashSet<String> {
    ["openai", "openai-codex", "opencode"]
        .iter()
        .map(|s| s.to_string())
        .collect()
}

fn versioned_sig(id: &str, phase: &str) -> String {
    json!({ "v": 1, "id": id, "phase": phase }).to_string()
}

fn convert_case(name: &str) -> (Model, Context, Option<ConvertResponsesMessagesOptions>) {
    let model = openai_model();
    match name {
        "basic-user-assistant" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "hi"),
                    Message::Assistant(assistant_message(
                        vec![text_content("on it", None)],
                        "anthropic-messages",
                        "anthropic",
                        "claude-opus-4-6",
                    )),
                    user_msg(2, "go"),
                ],
                tools: None,
            },
            None,
        ),
        "text-signature-versioned" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![text_content(
                            "answer",
                            Some(&versioned_sig("msg_123", "final_answer")),
                        )],
                        "openai-responses",
                        "openai",
                        "gpt-5.2",
                    )),
                ],
                tools: None,
            },
            None,
        ),
        "text-signature-legacy" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![text_content("answer", Some("legacy-id"))],
                        "openai-responses",
                        "openai",
                        "gpt-5.2",
                    )),
                ],
                tools: None,
            },
            None,
        ),
        "text-signature-cross-model-dropped" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![text_content(
                            "answer",
                            Some(&versioned_sig("msg_999", "final_answer")),
                        )],
                        "anthropic-messages",
                        "anthropic",
                        "claude-opus-4-6",
                    )),
                ],
                tools: None,
            },
            None,
        ),
        "tool-calls" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![tool_call_content("call_abc|fc_123", "base_tool", {
                            let mut m = Map::new();
                            m.insert("value".into(), json!("x"));
                            m
                        })],
                        "openai-responses",
                        "openai",
                        "gpt-5.2",
                    )),
                    tool_result("call_abc|fc_123", "base_tool", vec![text("done")], None),
                    user_msg(4, "Hello"),
                ],
                tools: Some(vec![tool("base_tool")]),
            },
            None,
        ),
        "foreign-tool-call-id" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![tool_call_content(
                            &format!("call_abc|{}", "x".repeat(80)),
                            "base_tool",
                            {
                                let mut m = Map::new();
                                m.insert("value".into(), json!("x"));
                                m
                            },
                        )],
                        "anthropic-messages",
                        "anthropic",
                        "claude-opus-4-6",
                    )),
                    tool_result(
                        &format!("call_abc|{}", "x".repeat(80)),
                        "base_tool",
                        vec![text("done")],
                        None,
                    ),
                ],
                tools: None,
            },
            None,
        ),
        "tool-result-images" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![tool_call_content("call_1", "base_tool", Map::new())],
                        "openai-responses",
                        "openai",
                        "gpt-5.2",
                    )),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![text("here"), image("AAAA")],
                        None,
                    ),
                ],
                tools: None,
            },
            None,
        ),
        "system-prompt-developer-role" => (
            model,
            Context {
                system_prompt: Some("You are helpful.".into()),
                messages: vec![user_msg(1, "hi")],
                tools: None,
            },
            None,
        ),
        "deferred-additional-tools" => (
            model,
            Context {
                system_prompt: None,
                messages: vec![
                    user_msg(1, "Hello"),
                    Message::Assistant(assistant_message(
                        vec![tool_call_content("call_1", "base_tool", Map::new())],
                        "openai-responses",
                        "openai",
                        "gpt-5.2",
                    )),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![text("done")],
                        Some(vec!["late_tool".into()]),
                    ),
                    user_msg(4, "Hello"),
                ],
                tools: Some(vec![tool("base_tool"), tool("late_tool")]),
            },
            Some(ConvertResponsesMessagesOptions {
                include_system_prompt: true,
                grammar_tool_input_properties: None,
                deferred_tools: None,
                deferred_tools_mode: Some(DeferredToolsMode::AdditionalTools),
                tool_options: ConvertResponsesToolsOptions {
                    strict: None,
                    supports_strict_mode: true,
                    supports_openai_grammar_tools: true,
                    defer_loading: false,
                },
            }),
        ),
        other => panic!("unknown convert case {other}"),
    }
}

fn convert_tools_case(name: &str) -> (Vec<Tool>, ConvertResponsesToolsOptions) {
    match name {
        "plain-tools" => (
            vec![tool("base_tool"), tool("late_tool")],
            ConvertResponsesToolsOptions {
                strict: None,
                supports_strict_mode: true,
                supports_openai_grammar_tools: false,
                defer_loading: false,
            },
        ),
        "grammar-tool" => (
            vec![grammar_tool()],
            ConvertResponsesToolsOptions {
                strict: None,
                supports_strict_mode: false,
                supports_openai_grammar_tools: true,
                defer_loading: false,
            },
        ),
        other => panic!("unknown convertTools case {other}"),
    }
}

// --- Tests ------------------------------------------------------------------

#[test]
fn convert_messages_golden() {
    let mut checked = 0;
    for (section, name, payload) in load_records() {
        if section != "convertMessages" {
            continue;
        }
        let (model, context, options) = convert_case(&name);
        let result =
            convert_responses_messages(&model, &context, &allowed_providers(), options.as_ref())
                .unwrap_or_else(|e| panic!("convert_responses_messages {name}: {e}"));
        assert_eq!(
            serde_json::to_string(&result).unwrap(),
            serde_json::to_string(&payload).unwrap(),
            "convertMessages {name}: compact JSON must match Pi byte-for-byte"
        );
        checked += 1;
    }
    assert!(
        checked >= 9,
        "expected >=9 convertMessages fixtures, got {checked}"
    );
}

#[test]
fn convert_tools_golden() {
    let mut checked = 0;
    for (section, name, payload) in load_records() {
        if section != "convertTools" {
            continue;
        }
        let (tools, options) = convert_tools_case(&name);
        let result =
            convert_responses_tools(&tools, &options).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(
            serde_json::to_string(&result).unwrap(),
            serde_json::to_string(&payload).unwrap(),
            "convertTools {name}: compact JSON must match Pi byte-for-byte"
        );
        checked += 1;
    }
    assert!(
        checked >= 2,
        "expected >=2 convertTools fixtures, got {checked}"
    );
}

fn stream_context(name: &str) -> Context {
    match name {
        "text-stream" => Context {
            system_prompt: None,
            messages: vec![user_msg(1, "hi")],
            tools: None,
        },
        "tool-call-stream" => Context {
            system_prompt: None,
            messages: vec![user_msg(1, "use the tool")],
            tools: Some(vec![tool("base_tool")]),
        },
        other => panic!("unknown stream case {other}"),
    }
}

fn event_without_partial(event: &AssistantMessageEvent) -> Value {
    let mut v = serde_json::to_value(event).expect("event to value");
    if let Some(obj) = v.as_object_mut() {
        obj.remove("partial");
        if obj.contains_key("message") || obj.contains_key("error") {
            for key in ["message", "error"] {
                if let Some(msg) = obj.get_mut(key).and_then(Value::as_object_mut) {
                    if let Some(ts) = msg.get_mut("timestamp") {
                        *ts = json!(0);
                    }
                }
            }
        }
    }
    v
}

#[tokio::test]
async fn stream_golden() {
    let mut checked = 0;
    for (section, name, payload) in load_records() {
        if section != "stream" {
            continue;
        }
        let sse_body = payload["sseBody"].as_str().expect("sseBody");
        let model = openai_model();
        let context = stream_context(&name);

        let mut simple = SimpleStreamOptions::default();
        simple.base.api_key = Some("fake-key".to_string());
        simple.base.transport = Some(
            std::sync::Arc::new(CannedTransport::new(sse_body.to_string()))
                as std::sync::Arc<dyn pirust_ai::http::DynTransport>,
        );
        let mut event_stream =
            pirust_ai::api::openai_responses::stream_simple(&model, &context, Some(simple));

        let mut tape: Vec<AssistantMessageEvent> = Vec::new();
        while let Some(event) = event_stream.next().await {
            tape.push(event);
        }
        let final_message = event_stream.result().await;

        let mut actual_final = serde_json::to_value(&final_message).unwrap();
        if let Some(ts) = actual_final.get_mut("timestamp") {
            *ts = json!(0);
        }
        assert_eq!(
            actual_final, payload["final"],
            "[{name}] final message must byte-match Pi's literal capture"
        );

        let expected_tape = payload["events"].as_array().expect("events array");
        assert_eq!(
            tape.len(),
            expected_tape.len(),
            "[{name}] tape length mismatch"
        );
        for (i, (event, expected)) in tape.iter().zip(expected_tape).enumerate() {
            assert_eq!(
                event_without_partial(event),
                *expected,
                "[{name}] tape event {i} mismatch"
            );
        }

        let terminal = tape.last().expect("non-empty tape");
        let terminal_message = match terminal {
            AssistantMessageEvent::Done { message, .. } => message,
            AssistantMessageEvent::Error { error, .. } => error,
            _ => panic!("terminal event is not done/error"),
        };
        let mut terminal_msg = serde_json::to_value(terminal_message).unwrap();
        if let Some(ts) = terminal_msg.get_mut("timestamp") {
            *ts = json!(0);
        }
        assert_eq!(
            terminal_msg, payload["final"],
            "[{name}] terminal event message must byte-match Pi's literal final"
        );

        checked += 1;
    }
    assert!(checked >= 2, "expected >=2 stream fixtures, got {checked}");
    eprintln!("openai-responses stream golden: {checked} scenarios byte-verified");
}
