//! Byte-compatibility tests for the `openai-completions` conversion layer
//! against real Pi output (the oracle).
//!
//! Fixtures: `tests/fixtures/pi/openai-completions/cases.jsonl`, generated by
//! `scripts/gen-openai-completions-oracle.mjs` which drives Pi's REAL
//! `convertMessages` (and `streamSimple` for the buildParams section) offline.
//! This test replays the `convertMessages` records through the Rust port
//! (`pirust_ai::api::openai_completions::convert_messages`) and asserts the
//! re-serialized compact JSON is byte-identical to Pi's literal output.
//!
//! The `buildParams` records are pinned here too (the fixture must not drift)
//! but the full `buildParams` port lands with the stream wave; they are loaded
//! to verify the fixture stays intact, not replayed yet.

use std::collections::HashMap;
use std::path::PathBuf;

use pirust_ai::api::openai_completions::{
    convert_messages, DeferredToolsMode, MaxTokensField, ResolvedOpenAICompletionsCompat,
    ThinkingFormat,
};
use pirust_ai::types::content::{
    AssistantContent, TextContent, ThinkingContent, ToolCall, UserContent,
};
use pirust_ai::types::ids::{Api, ProviderId, SessionAffinityFormat, StopReason};
use pirust_ai::types::message::{
    AssistantMessage, Context, Message, Tool, ToolResultMessage, UserMessage, UserMessageContent,
};
use pirust_ai::types::model::{Modality, Model, ModelCost, ModelCostRates};
use serde_json::{json, Map, Value};

fn fixtures_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/pi")
}

fn load_records() -> Vec<(String, String, Value)> {
    let path = fixtures_dir().join("openai-completions/cases.jsonl");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("read {path:?} ({e}); run: node scripts/gen-openai-completions-oracle.mjs")
    });
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            let v: Value = serde_json::from_str(l).expect("fixture line is JSON");
            let section = v["section"].as_str().unwrap().to_string();
            let name = v["name"].as_str().unwrap().to_string();
            (section, name, v["payload"].clone())
        })
        .collect()
}

// --- Fixture reconstruction helpers (mirror the oracle script) --------------

fn model(
    id: &str,
    provider: &str,
    reasoning: bool,
    input: Vec<Modality>,
    compat: Option<Value>,
) -> Model {
    Model {
        id: id.into(),
        name: "Test".into(),
        api: Api::from("openai-completions"),
        provider: ProviderId::from(provider),
        base_url: "http://127.0.0.1:9/v1".into(),
        reasoning,
        thinking_level_map: None,
        input,
        cost: ModelCost {
            rates: ModelCostRates {
                input: 0.0,
                output: 0.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            tiers: None,
        },
        context_window: 128_000,
        max_tokens: 4096,
        headers: None,
        compat,
    }
}

fn base_compat() -> ResolvedOpenAICompletionsCompat {
    ResolvedOpenAICompletionsCompat {
        supports_store: true,
        supports_developer_role: true,
        supports_reasoning_effort: true,
        supports_usage_in_streaming: true,
        supports_finish_reason: true,
        max_tokens_field: MaxTokensField::MaxCompletionTokens,
        requires_tool_result_name: false,
        requires_assistant_after_tool_result: false,
        requires_thinking_as_text: false,
        requires_reasoning_content_on_assistant_messages: false,
        thinking_format: ThinkingFormat::Openai,
        open_router_routing: json!({}),
        vercel_gateway_routing: json!({}),
        chat_template_kwargs: json!({}),
        chat_template_args: json!({}),
        zai_tool_stream: false,
        supports_thinking_token_budget: false,
        thinking_token_budget_field: None,
        supports_strict_mode: true,
        supports_openai_grammar_tools: false,
        cache_control_format: None,
        send_session_affinity_headers: false,
        deferred_tools_mode: None,
        session_affinity_format: SessionAffinityFormat::Openai,
        supports_long_cache_retention: true,
    }
}

fn user_msg(timestamp: i64, content: impl Into<String>) -> Message {
    Message::User(UserMessage {
        role: pirust_ai::types::message::UserRole::User,
        content: UserMessageContent::Text(content.into()),
        timestamp,
    })
}

fn usage0() -> pirust_ai::types::usage::Usage {
    pirust_ai::types::usage::Usage {
        input: 0,
        output: 0,
        cache_read: 0,
        cache_write: 0,
        cache_write1h: None,
        reasoning: None,
        total_tokens: Some(0),
        cost: pirust_ai::types::usage::Cost {
            input: 0.0,
            output: 0.0,
            cache_read: 0.0,
            cache_write: 0.0,
            total: 0.0,
        },
    }
}

fn assistant_base(stop_reason: StopReason) -> AssistantMessage {
    AssistantMessage {
        role: pirust_ai::types::message::AssistantRole::Assistant,
        content: Vec::new(),
        api: Api::from("anthropic-messages"),
        provider: ProviderId::from("anthropic"),
        model: Some("claude-opus-4-6".into()),
        response_model: None,
        diagnostics: None,
        usage: usage0(),
        stop_reason,
        timestamp: 2,
        response_id: None,
        raw_stop_reason: None,
        error_message: None,
        end_turn: None,
    }
}

fn assistant_text(text: &str) -> Message {
    let mut a = assistant_base(StopReason::Stop);
    a.content
        .push(AssistantContent::Text(TextContent::new(text)));
    Message::Assistant(a)
}

fn assistant_thinking(thinking: &str, signature: &str) -> Message {
    let mut a = assistant_base(StopReason::Stop);
    a.content.push(AssistantContent::Thinking(ThinkingContent {
        kind: pirust_ai::types::content::ThinkingTag::Thinking,
        thinking: thinking.into(),
        thinking_signature: Some(signature.into()),
        redacted: None,
    }));
    Message::Assistant(a)
}

fn assistant_tool_call(
    id: &str,
    name: &str,
    arguments: Map<String, Value>,
    model_id: &str,
) -> Message {
    let mut a = assistant_base(StopReason::ToolUse);
    a.model = Some(model_id.into());
    a.content.push(AssistantContent::ToolCall(ToolCall {
        kind: pirust_ai::types::content::ToolCallTag::ToolCall,
        id: id.into(),
        name: name.into(),
        arguments,
        thought_signature: None,
        namespace: None,
        partial_json: None,
    }));
    Message::Assistant(a)
}

fn tool_result(
    tool_call_id: &str,
    tool_name: &str,
    content: Vec<UserContent>,
    added_tool_names: Option<Vec<String>>,
) -> Message {
    Message::ToolResult(ToolResultMessage {
        role: pirust_ai::types::message::ToolResultRole::ToolResult,
        tool_call_id: tool_call_id.into(),
        tool_name: tool_name.into(),
        content,
        details: None,
        added_tool_names,
        is_error: false,
        timestamp: 3,
    })
}

fn tool(name: &str) -> Tool {
    Tool {
        name: name.into(),
        description: format!("The {name} tool"),
        parameters: json!({
            "type": "object",
            "required": ["value"],
            "properties": { "value": { "type": "string" } }
        }),
        constrained_sampling: None,
    }
}

fn context(messages: Vec<Message>, tools: Option<Vec<Tool>>) -> Context {
    Context {
        system_prompt: None,
        messages,
        tools,
    }
}

/// Rebuild the scenario inputs for a `convertMessages` fixture record and run
/// the Rust port, returning the compact JSON of the result.
fn run_convert_case(name: &str) -> String {
    let (context, model, compat, grammar_props): (
        Context,
        Model,
        ResolvedOpenAICompletionsCompat,
        Option<HashMap<String, String>>,
    ) = match name {
        "basic-user-assistant" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_text("on it"),
                    user_msg(2, "go"),
                ],
                None,
            ),
            model("test-model", "together", false, vec![Modality::Text], None),
            base_compat(),
            None,
        ),
        "thinking-signature" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_thinking("let me think", "reasoning"),
                    assistant_text("answer"),
                ],
                None,
            ),
            model(
                "test-model",
                "opencode-go",
                true,
                vec![Modality::Text],
                None,
            ),
            base_compat(),
            None,
        ),
        "thinking-as-text" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_thinking("step one", "signature"),
                    assistant_text("done"),
                ],
                None,
            ),
            model("test-model", "together", true, vec![Modality::Text], None),
            {
                let mut c = base_compat();
                c.requires_thinking_as_text = true;
                c
            },
            None,
        ),
        "deepseek-reasoning-content" => (
            context(vec![user_msg(1, "Hello"), assistant_text("ok")], None),
            model("test-model", "deepseek", true, vec![Modality::Text], None),
            {
                let mut c = base_compat();
                c.requires_reasoning_content_on_assistant_messages = true;
                c
            },
            None,
        ),
        "tool-calls" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call(
                        "call_1",
                        "base_tool",
                        {
                            let mut m = Map::new();
                            m.insert("value".into(), json!("x"));
                            m
                        },
                        "test-model",
                    ),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        None,
                    ),
                    user_msg(4, "thanks"),
                ],
                Some(vec![tool("base_tool")]),
            ),
            model("test-model", "together", false, vec![Modality::Text], None),
            base_compat(),
            None,
        ),
        "pipe-tool-call-ids" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call(
                        "call_abc|item_12345",
                        "base_tool",
                        {
                            let mut m = Map::new();
                            m.insert("value".into(), json!("x"));
                            m
                        },
                        "gpt",
                    ),
                    tool_result(
                        "call_abc|item_12345",
                        "base_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        None,
                    ),
                    user_msg(4, "Hello"),
                ],
                None,
            ),
            model(
                "test-model",
                "github-copilot",
                false,
                vec![Modality::Text],
                None,
            ),
            base_compat(),
            None,
        ),
        "pipe-tool-call-id-hash" => {
            let long = format!("call_abc|{}", "long-item-".to_string() + &"x".repeat(80));
            (
                context(
                    vec![
                        user_msg(1, "Hello"),
                        assistant_tool_call(
                            &long,
                            "base_tool",
                            {
                                let mut m = Map::new();
                                m.insert("value".into(), json!("x"));
                                m
                            },
                            "test-model",
                        ),
                        tool_result(
                            &long,
                            "base_tool",
                            vec![UserContent::Text(TextContent::new("done"))],
                            None,
                        ),
                        user_msg(4, "Hello"),
                    ],
                    None,
                ),
                model(
                    "test-model",
                    "github-copilot",
                    false,
                    vec![Modality::Text],
                    None,
                ),
                base_compat(),
                None,
            )
        }
        "assistant-after-tool-result" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call("call_1", "base_tool", Map::new(), "test-model"),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        None,
                    ),
                    user_msg(4, "thanks"),
                ],
                Some(vec![tool("base_tool")]),
            ),
            model("test-model", "together", false, vec![Modality::Text], None),
            {
                let mut c = base_compat();
                c.requires_assistant_after_tool_result = true;
                c
            },
            None,
        ),
        "tool-result-images" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call("call_1", "base_tool", Map::new(), "test-model"),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![
                            UserContent::Text(TextContent::new("here is the image")),
                            UserContent::Image(pirust_ai::types::content::ImageContent {
                                kind: pirust_ai::types::content::ImageTag::Image,
                                data: "AAAA".into(),
                                mime_type: "image/png".into(),
                            }),
                        ],
                        None,
                    ),
                ],
                None,
            ),
            model(
                "test-model",
                "together",
                false,
                vec![Modality::Text, Modality::Image],
                None,
            ),
            base_compat(),
            None,
        ),
        "kimi-deferred-tools" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call("call_1", "base_tool", Map::new(), "test-model"),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        Some(vec!["late_tool".into()]),
                    ),
                    user_msg(4, "thanks"),
                ],
                Some(vec![tool("base_tool"), tool("late_tool")]),
            ),
            model(
                "test-model",
                "moonshotai",
                false,
                vec![Modality::Text],
                None,
            ),
            {
                let mut c = base_compat();
                c.deferred_tools_mode = Some(DeferredToolsMode::Kimi);
                c
            },
            None,
        ),
        "tool-result-name" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call("call_1", "base_tool", Map::new(), "test-model"),
                    tool_result(
                        "call_1",
                        "base_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        None,
                    ),
                ],
                Some(vec![tool("base_tool")]),
            ),
            model("test-model", "together", false, vec![Modality::Text], None),
            {
                let mut c = base_compat();
                c.requires_tool_result_name = true;
                c
            },
            None,
        ),
        "grammar-custom-tool-call" => (
            context(
                vec![
                    user_msg(1, "Hello"),
                    assistant_tool_call(
                        "call_g",
                        "grammar_tool",
                        {
                            let mut m = Map::new();
                            m.insert("value".into(), json!("input string"));
                            m
                        },
                        "test-model",
                    ),
                    tool_result(
                        "call_g",
                        "grammar_tool",
                        vec![UserContent::Text(TextContent::new("done"))],
                        None,
                    ),
                    user_msg(4, "Hello"),
                ],
                None,
            ),
            model("test-model", "together", false, vec![Modality::Text], None),
            base_compat(),
            Some(HashMap::from([(
                "grammar_tool".to_string(),
                "value".to_string(),
            )])),
        ),
        "system-prompt-developer-role" => (
            Context {
                system_prompt: Some("You are a helpful assistant.".into()),
                messages: vec![user_msg(1, "hi")],
                tools: None,
            },
            model("test-model", "together", true, vec![Modality::Text], None),
            base_compat(),
            None,
        ),
        other => panic!("unknown convertMessages fixture case: {other}"),
    };

    let params = convert_messages(&model, &context, &compat, grammar_props.as_ref())
        .unwrap_or_else(|e| panic!("convert_messages({name}) failed: {e}"));
    serde_json::to_string(&params).unwrap()
}

/// Every `convertMessages` fixture record must replay byte-identically.
#[test]
fn convert_messages_matches_oracle() {
    let records = load_records();
    let convert_records: Vec<_> = records
        .iter()
        .filter(|(section, _, _)| section == "convertMessages")
        .collect();
    assert!(!convert_records.is_empty(), "no convertMessages records");
    let mut failures = Vec::new();
    for (_, name, expected) in &convert_records {
        let actual = run_convert_case(name);
        let expected_str = serde_json::to_string(expected).expect("serialize expected payload");
        if actual != expected_str {
            failures.push(format!(
                "{name}:\n  expected {}\n  actual   {}",
                expected_str, actual
            ));
        }
    }
    if !failures.is_empty() {
        panic!(
            "convert_messages mismatch vs Pi oracle:\n{}",
            failures.join("\n")
        );
    }
}

/// Every `buildParams` fixture record must replay byte-identically through the
/// Rust port (this replaces the placeholder `build_params_records_present`).
#[test]
fn build_params_matches_oracle() {
    use pirust_ai::api::openai_completions::{build_params, clamp_max_tokens_to_context};
    use pirust_ai::api::OpenAICompletionsOptions;

    let records = load_records();
    let build_records: Vec<_> = records
        .iter()
        .filter(|(section, _, _)| section == "buildParams")
        .collect();
    assert!(!build_records.is_empty(), "no buildParams records");

    let mut failures = Vec::new();
    for (_, name, expected) in &build_records {
        // Rebuild model/context per scenario (mirrors the oracle's modelScenarios).
        let (model, context): (Model, Context) = match name.as_str() {
            "deepseek" => (
                Model {
                    id: "deepseek-v4-flash".into(),
                    name: "DeepSeek V4 Flash".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("deepseek"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: true,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 1_000_000,
                    max_tokens: 384_000,
                    headers: None,
                    compat: Some(json!({
                        "supportsStore": false,
                        "supportsDeveloperRole": false,
                        "maxTokensField": "max_tokens",
                        "requiresReasoningContentOnAssistantMessages": true,
                        "thinkingFormat": "deepseek"
                    })),
                },
                context(
                    vec![
                        user_msg(1, "Hello"),
                        assistant_tool_call("call_1", "base_tool", Map::new(), "deepseek-v4-flash"),
                        tool_result(
                            "call_1",
                            "base_tool",
                            vec![UserContent::Text(TextContent::new("done"))],
                            None,
                        ),
                        user_msg(4, "thanks"),
                    ],
                    Some(vec![tool("base_tool")]),
                ),
            ),
            "together" => (
                Model {
                    id: "meta-llama/Llama-3.3-70B-Instruct-Turbo".into(),
                    name: "Llama 3.3 70B Instruct Turbo".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("together"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: false,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 131_072,
                    max_tokens: 131_072,
                    headers: None,
                    compat: Some(json!({
                        "supportsStore": false,
                        "supportsDeveloperRole": false,
                        "supportsReasoningEffort": false,
                        "maxTokensField": "max_tokens",
                        "thinkingFormat": "together",
                        "supportsStrictMode": false,
                        "supportsLongCacheRetention": false
                    })),
                },
                context(vec![user_msg(1, "hi")], Some(vec![tool("base_tool")])),
            ),
            "zai" => (
                Model {
                    id: "glm-4.7".into(),
                    name: "GLM-4.7".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("zai"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: true,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 204_800,
                    max_tokens: 131_072,
                    headers: None,
                    compat: Some(json!({
                        "supportsStore": false,
                        "supportsDeveloperRole": false,
                        "supportsReasoningEffort": false,
                        "maxTokensField": "max_tokens",
                        "thinkingFormat": "zai",
                        "zaiToolStream": true
                    })),
                },
                context(vec![user_msg(1, "hi")], None),
            ),
            "openrouter-anthropic" => (
                Model {
                    id: "anthropic/claude-3-haiku".into(),
                    name: "Claude 3 Haiku".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("openrouter"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: false,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 200_000,
                    max_tokens: 4096,
                    headers: None,
                    compat: Some(json!({
                        "thinkingFormat": "openrouter",
                        "cacheControlFormat": "anthropic"
                    })),
                },
                context(vec![user_msg(1, "hi")], Some(vec![tool("base_tool")])),
            ),
            "nvidia" => (
                Model {
                    id: "meta/llama-3.1-70b-instruct".into(),
                    name: "Llama 3.1 70B Instruct".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("nvidia"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: false,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 128_000,
                    max_tokens: 4096,
                    headers: None,
                    compat: Some(json!({
                        "supportsStore": false,
                        "supportsDeveloperRole": false,
                        "supportsReasoningEffort": false,
                        "maxTokensField": "max_tokens",
                        "supportsStrictMode": false,
                        "supportsLongCacheRetention": false
                    })),
                },
                context(vec![user_msg(1, "hi")], Some(vec![tool("base_tool")])),
            ),
            "moonshot-kimi" => (
                Model {
                    id: "kimi-k2-0711-preview".into(),
                    name: "Kimi K2 0711 Preview".into(),
                    api: Api::from("openai-completions"),
                    provider: ProviderId::from("moonshotai"),
                    base_url: "http://127.0.0.1:9/v1".into(),
                    reasoning: false,
                    thinking_level_map: None,
                    input: vec![Modality::Text],
                    cost: ModelCost {
                        rates: ModelCostRates {
                            input: 0.0,
                            output: 0.0,
                            cache_read: 0.0,
                            cache_write: 0.0,
                        },
                        tiers: None,
                    },
                    context_window: 131_072,
                    max_tokens: 16_384,
                    headers: None,
                    compat: Some(json!({
                        "supportsStore": false,
                        "supportsDeveloperRole": false,
                        "supportsReasoningEffort": false,
                        "maxTokensField": "max_tokens",
                        "supportsStrictMode": false,
                        "thinkingFormat": "deepseek"
                    })),
                },
                context(vec![user_msg(1, "hi")], Some(vec![tool("base_tool")])),
            ),
            other => panic!("unknown buildParams fixture case: {other}"),
        };

        // Mirror streamSimple → buildBaseOptions: maxTokens = clamp(model.maxTokens).
        let clamped = clamp_max_tokens_to_context(&model, &context, model.max_tokens);
        let options = OpenAICompletionsOptions {
            base: pirust_ai::api::StreamOptions {
                max_tokens: Some(clamped),
                ..Default::default()
            },
            tool_choice: None,
            reasoning_effort: None,
            thinking_budgets: None,
        };

        let compat = pirust_ai::api::openai_completions::get_compat(&model);
        let actual = build_params(&model, &context, Some(&options), Some(&compat))
            .unwrap_or_else(|e| panic!("build_params({name}) failed: {e}"));
        let actual_str = serde_json::to_string(&actual).unwrap();
        let expected_str = serde_json::to_string(expected).expect("serialize expected payload");
        if actual_str != expected_str {
            failures.push(format!(
                "{name}:\n  expected {}\n  actual   {}",
                expected_str, actual_str
            ));
        }
    }
    if !failures.is_empty() {
        panic!(
            "build_params mismatch vs Pi oracle:\n{}",
            failures.join("\n")
        );
    }
}

/// The buildParams records must remain present (pinned for the buildParams
/// wave); assert the fixture has them so `--check` can't silently drop them.
#[test]
fn build_params_records_present() {
    let records = load_records();
    let build: Vec<_> = records
        .iter()
        .filter(|(section, _, _)| section == "buildParams")
        .collect();
    assert!(
        build.len() >= 6,
        "expected >=6 buildParams records, got {}",
        build.len()
    );
}
